// Quotes shown in the avatar picker speech bubble.
// Keyed by trainer id. Falls back to a generic line if missing.

export const TRAINER_QUOTES: Record<string, string> = {
  red: "Words aren't necessary. Let our battle speak.",
  blue: "Smell ya later! Let's see what you've got.",
  green: "I'm not gonna lose to a rookie like you.",
  ash: "I'll battle with everything I've got — that's a promise!",
  gary: "I've got a Pokémon that can beat yours any day.",
  leaf: "Adventure favors the bold. Let's go!",
  ethan: "I'm aiming to be the best — care to test me?",
  lyra: "Let's give it our all and have some fun!",
  brendan: "I'm not holding back, so don't you either!",
  may: "Get ready — I battle with style!",
  lucas: "Every battle teaches us something new.",
  dawn: "No backing down now. Let's go, partner!",
  hilbert: "Truth or ideals — I'll show you what I believe in.",
  hilda: "I'll battle with all my heart!",
  nate: "Let's heat this battle up!",
  rosa: "I'm ready to give it my all — are you?",
  calem: "Style and strength — that's how I battle.",
  serena: "Let's make this a memorable battle!",
  elio: "Alola! Let's have a great battle!",
  selene: "I'm gonna give it everything I've got!",
  victor: "Time for our gym challenge!",
  gloria: "Let's have a smashing battle!",
  misty: "My policy is an all-out offensive with Water Pokémon!",
  brock: "I take pride in my rock-hard willpower!",
  ltsurge: "Hah! You'll be shocked at my power!",
  erika: "Oh… I must have dozed off. Very well, I shall battle.",
  sabrina: "I had a vision of your arrival.",
  koga: "Fwahaha! A mere child like you dares to challenge me?",
  blaine: "My quiz is over. Now it's time for a battle!",
  giovanni: "So! I must say, I am impressed you got here.",
  janine: "Hee hoo hoo! I am Janine of the Fuchsia Gym!",
  falkner: "I'll show you the real power of the magnificent bird Pokémon!",
  bugsy: "I never lose when it comes to bug Pokémon!",
  whitney: "Hee hee! Everyone was into Pokémon, so I got into it, too!",
  morty: "Now is the time to see how well we will battle together.",
  chuck: "Wahahah! So you've come to challenge me!",
  jasmine: "Um… I'm sorry… My Pokémon got tougher.",
  pryce: "I am Pryce, the winter-loving Ice user.",
  clair: "I am Clair. The world's best dragon master.",
  norman: "I'm proud of you for working your way here.",
  wattson: "Wahahahah! Fine, then! Show me your power!",
  flannery: "Welcome! No, wait. Let me change that.",
  winona: "I am the leader of Fortree Gym, Winona.",
  roark: "I want to see your power as a Trainer.",
  gardenia: "You and your Pokémon look like you're sparkling with energy.",
  crasher_wake: "CRASHER WAKE! That's me. Cresselia… Mesprit… I love them!",
  fantina: "I am the leader of Hearthome Gym — Fantina!",
  byron: "Hmm! I see you've got a look of toughness about you.",
  candice: "Sorry to keep you waiting. You looked at me funny.",
  volkner: "I'm Volkner, the Gym Leader. Let's see your stuff.",
  cilan: "I think I'll get a little more serious now.",
  chili: "I'm Chili! I light things up with fire-type Pokémon!",
  cress: "I'm Cress, a water-type specialist.",
  lenora: "Now, my dear challenger! Let's see what you and your Pokémon can do!",
  burgh: "Art and battle are one and the same.",
  elesa: "Now then, my pretty challenger, it's time to dance.",
  clay: "Hrmph. I'm not a fan of mavericks who got no clue what they're doing.",
  skyla: "All right, then — let's get our battle started.",
  brycen: "If a strong Trainer's Pokémon are also strong, they can win!",
  drayden: "Heh-heh-heh! That's a great look in your eyes!",
  iris: "Yeah! I'm gonna battle with you for everything I've got!",
  viola: "Whether it's the tears of frustration that follow a loss, or the blossoming of joy that comes with victory…",
  grant: "Only by overcoming the wall that looms before you can you grow.",
  korrina: "Time for Lady Korrina's big appearance!",
  ramos: "Ho-ho-hoh! So ye're me challenger?",
  clemont: "OK, the future is now! Science is amazing!",
  valerie: "Oh, if it isn't a young Trainer…",
  olympia: "Future. Battle. Tides. Come.",
  wulfric: "What do you do when an unstoppable foe stands in your way?",
  ilima: "I am Trial Captain Ilima. It is a pleasure to meet you.",
  hala: "Stand still! Stand still and listen to the sound of your own heart!",
  olivia: "Aren't you just a breath of fresh air?",
  nanu: "I'm gonna show you that there's much more to a Trainer than just bein' tough.",
  hapu: "I am Hapu — the kahuna of Poni Island.",
  milo: "I'm Milo, the Grass-type Gym Leader.",
  nessa: "I'll show you what a real Water-type Gym Leader can do.",
  kabu: "I will give my all to defeat you.",
  bea: "I won't lose. Not now. Not ever.",
  allister: "M-my name's Allister… Pleased to meetcha.",
  opal: "Let's see how you do against this old lady!",
  gordie: "Time for you to rock and roll with me!",
  melony: "I'm Melony. Stay warm out there.",
  piers: "I'd rather sing than battle, truth be told.",
  raihan: "I'm Raihan, the Dragon-type Gym Leader.",
  cynthia: "Every Pokémon battle is a precious treasure.",
  lance: "I've been waiting for a challenger like you.",
  steven: "Let me see the power you wield with your partner.",
  wallace: "I shall show you the beauty of a true battle.",
  alder: "I've been waiting for a strong young Trainer like you.",
  iris_champ: "I'm the strongest Dragon-type Trainer in the world!",
  diantha: "All my dearest wishes will be on the line in our match!",
  kukui: "Let's see how my favorite student battles!",
  hau: "Let's have a battle as awesome as malasada!",
  leon: "My time as Champion has been an unbroken streak of victories!",
  oak: "There are still countless mysteries yet to be uncovered!",
  jessie: "Prepare for trouble!",
  james: "And make it double!",
  meowth: "Meowth, that's right!",
  n: "Pokémon and people aren't meant to be used.",
  ghetsis: "Pokémon exist to make my dreams a reality!",
  guzma: "I'm Guzma, and I'm gonna make you cry!",
  lillie: "Let's both do our best!",
};

export function trainerQuote(id: string, name: string): string {
  return TRAINER_QUOTES[id] ?? `I'm ${name}. Let's have a great battle!`;
}
