// AUTO-GENERATED by scripts/build-trainers.ts. Do not edit.
import data from "./trainer-data.generated.json";
export interface TrainerSprite {
  id: string;
  name: string;
  url: string;
  gen: 3 | 4 | 5 | "masters";
}
export const TRAINER_SPRITES: TrainerSprite[] = data as TrainerSprite[];
