// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
// Wraps TABLE["cute-charm"] from lib/pvp-type-abilities.ts by reference; the
// behavior itself is authored there, not here.
import type { TypeAbilityDef } from "./type-def";
import { TABLE } from "../../../lib/pvp-type-abilities";

export const cuteCharm: TypeAbilityDef = {
  id: "cute-charm",
  pvp: TABLE["cute-charm"],
};
