// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
// Wraps TABLE["moxie"] from lib/pvp-type-abilities.ts by reference; the
// behavior itself is authored there, not here.
import type { TypeAbilityDef } from "./type-def";
import { TABLE } from "../../../lib/pvp-type-abilities";

export const moxie: TypeAbilityDef = {
  id: "moxie",
  pvp: TABLE["moxie"],
};
