// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
// Wraps TABLE["poison-touch"] from lib/pvp-type-abilities.ts by reference; the
// behavior itself is authored there, not here.
import type { TypeAbilityDef } from "./type-def";
import { TABLE } from "../../../lib/pvp-type-abilities";

export const poisonTouch: TypeAbilityDef = {
  id: "poison-touch",
  pvp: TABLE["poison-touch"],
};
