// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
// Wraps TABLE["synthesis"] from lib/pvp-type-abilities.ts by reference; the
// behavior itself is authored there, not here.
import type { TypeAbilityDef } from "./type-def";
import { TABLE } from "../../../lib/pvp-type-abilities";

export const synthesis: TypeAbilityDef = {
  id: "synthesis",
  pvp: TABLE["synthesis"],
};
