// Nearby-Battle (PvP) wiring for the base (non-legendary) type abilities. One
// file per ability, generated by scripts/gen-type-content.ts from the live
// TABLE in lib/pvp-type-abilities.ts.
//
// Unlike items/statuses/rolled, these entries are executable behavior (damage
// tweaks, timing predicates), not declarative data — the same reason
// content/abilities/signature/ wraps rather than reimplements. lib/pvp-type-
// abilities.ts stays the single source of truth for the actual logic; these
// files only give each ability its own file per the architecture doc's
// directory map and expose it through a typed registry.
import type { AbilityId } from "../rolled/rolled-def";
import type { TypeAbilityPvp } from "../../../lib/pvp-type-abilities";

export interface TypeAbilityDef {
  id: AbilityId;
  pvp: TypeAbilityPvp;
}
