// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
// Wraps TABLE["volt-absorb"] from lib/pvp-type-abilities.ts by reference; the
// behavior itself is authored there, not here.
import type { TypeAbilityDef } from "./type-def";
import { TABLE } from "../../../lib/pvp-type-abilities";

export const voltAbsorb: TypeAbilityDef = {
  id: "volt-absorb",
  pvp: TABLE["volt-absorb"],
};
