import { useEffect } from "react";

/**
 * Registers the service worker generated by vite-plugin-pwa.
 *
 * TanStack Start has no static index.html, so the plugin's `injectRegister`
 * has nowhere to inject. We register manually on the client.
 *
 * Skipped in iframes and Lovable preview hosts to avoid stale-cache issues
 * inside the editor.
 */
export function PwaRegister() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("serviceWorker" in navigator)) return;

    const inIframe = (() => {
      try {
        return window.self !== window.top;
      } catch {
        return true;
      }
    })();
    const host = window.location.hostname;
    const isPreview = host.includes("id-preview--") || host.includes("lovableproject.com");

    if (inIframe || isPreview) {
      navigator.serviceWorker
        .getRegistrations()
        .then((regs) => regs.forEach((r) => r.unregister()))
        .catch(() => {});
      return;
    }

    import("virtual:pwa-register")
      .then(({ registerSW }) => {
        registerSW({ immediate: true });
      })
      .catch(() => {});
  }, []);

  return null;
}
