// One-shot script: fetch all Pokémon (id, name, slug, types) from PokeAPI
// and write src/lib/pokemon-data.generated.ts.
// Run with: bun scripts/build-pokemon.ts
import { writeFileSync } from "node:fs";

const TYPES = [
  "normal","fire","water","electric","grass","ice","fighting","poison","ground",
  "flying","psychic","bug","rock","ghost","dragon","dark","steel","fairy",
];

interface Entry { id: number; slug: string; name: string; types: string[]; }

async function main() {
  const map = new Map<number, Entry>();

  // 1) names + slugs (limit covers through Gen 9)
  const list = await fetch("https://pokeapi.co/api/v2/pokemon?limit=1025").then(r => r.json());
  for (const p of list.results as { name: string; url: string }[]) {
    const id = Number(p.url.split("/").filter(Boolean).pop());
    if (!Number.isFinite(id) || id > 1025) continue;
    const slug = p.name; // PokeAPI slug is what pokemondb also uses (e.g. "mr-mime", "ho-oh")
    const pretty = slug
      .split("-")
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ");
    map.set(id, { id, slug, name: pretty, types: [] });
  }

  // 2) types via 18 type endpoints
  for (const t of TYPES) {
    const data = await fetch(`https://pokeapi.co/api/v2/type/${t}`).then(r => r.json());
    for (const m of data.pokemon as { pokemon: { url: string } }[]) {
      const id = Number(m.pokemon.url.split("/").filter(Boolean).pop());
      const e = map.get(id);
      if (e && !e.types.includes(t)) e.types.push(t);
    }
    console.log(`types ${t} done`);
  }

  const all = [...map.values()].sort((a, b) => a.id - b.id).filter(e => e.types.length > 0);

  const body =
`// AUTO-GENERATED by scripts/build-pokemon.ts. Do not edit.
export type PokeType =
  | "normal" | "fire" | "water" | "electric" | "grass" | "ice"
  | "fighting" | "poison" | "ground" | "flying" | "psychic"
  | "bug" | "rock" | "ghost" | "dragon" | "dark" | "steel" | "fairy";

export interface PokeEntry {
  id: number;
  slug: string;
  name: string;
  types: PokeType[];
}

export const ALL_POKEMON: PokeEntry[] = ${JSON.stringify(all, null, 2)} as PokeEntry[];
`;
  writeFileSync("src/lib/pokemon-data.generated.ts", body);
  console.log(`wrote ${all.length} pokemon`);
}

main().catch(e => { console.error(e); process.exit(1); });
