// One-shot script: fetch all Pokémon (id, name, slug, types, evolution chain) from PokeAPI
// and write src/lib/pokemon-data.generated.ts.
// Run with: bun scripts/build-pokemon.ts
import { writeFileSync } from "node:fs";

const TYPES = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy",
];

interface Entry {
  id: number;
  slug: string;
  name: string;
  types: string[];
  evolvesFromId: number | null;
  evolvesToIds: number[];
  evolutionStage: 1 | 2 | 3;
  isFullyEvolved: boolean;
  evolutionChainUrl?: string | null;
}

async function batched<T>(items: T[], size: number, fn: (item: T) => Promise<void>, label: string) {
  for (let i = 0; i < items.length; i += size) {
    await Promise.all(items.slice(i, i + size).map(fn));
    console.log(`${label} ${Math.min(i + size, items.length)}/${items.length}`);
  }
}

async function main() {
  const map = new Map<number, Entry>();

  // 1) names + slugs (limit covers through Gen 9)
  const list = await fetch("https://pokeapi.co/api/v2/pokemon?limit=1025").then((r) => r.json());
  for (const p of list.results as { name: string; url: string }[]) {
    const id = Number(p.url.split("/").filter(Boolean).pop());
    if (!Number.isFinite(id) || id > 1025) continue;
    const slug = p.name;
    const pretty = slug
      .split("-")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ");
    map.set(id, {
      id,
      slug,
      name: pretty,
      types: [],
      evolvesFromId: null,
      evolvesToIds: [],
      evolutionStage: 1,
      isFullyEvolved: true,
      evolutionChainUrl: null,
    });
  }

  // 2) types via 18 type endpoints
  for (const t of TYPES) {
    const data = await fetch(`https://pokeapi.co/api/v2/type/${t}`).then((r) => r.json());
    for (const m of data.pokemon as { pokemon: { url: string } }[]) {
      const id = Number(m.pokemon.url.split("/").filter(Boolean).pop());
      const e = map.get(id);
      if (e && !e.types.includes(t)) e.types.push(t);
    }
    console.log(`types ${t} done`);
  }

  // 3) species + evolution chain url
  await batched(
    [...map.values()],
    50,
    async (entry) => {
      try {
        const sp = await fetch(`https://pokeapi.co/api/v2/pokemon-species/${entry.id}`).then((r) =>
          r.json(),
        );
        entry.evolvesFromId = sp.evolves_from_species
          ? Number(sp.evolves_from_species.url.split("/").filter(Boolean).pop())
          : null;
        entry.evolutionChainUrl = sp.evolution_chain?.url ?? null;
      } catch {
        entry.evolvesFromId = null;
        entry.evolutionChainUrl = null;
      }
    },
    "species",
  );

  // 4) fetch unique chains
  const chainUrls = new Set<string>();
  for (const e of map.values()) if (e.evolutionChainUrl) chainUrls.add(e.evolutionChainUrl);
  const chainsByUrl = new Map<string, unknown>();
  await batched(
    [...chainUrls],
    50,
    async (url) => {
      try {
        const data = await fetch(url).then((r) => r.json());
        chainsByUrl.set(url, data.chain);
      } catch {
        /* ignore fetch/parse errors for this evolution chain */
      }
    },
    "chains",
  );

  // 5) walk chains
  type ChainNode = { species: { url: string }; evolves_to: ChainNode[] };
  function walkChain(node: ChainNode, stage: number) {
    const speciesId = Number(node.species.url.split("/").filter(Boolean).pop());
    const entry = map.get(speciesId);
    if (entry) {
      entry.evolutionStage = Math.min(3, stage) as 1 | 2 | 3;
      entry.evolvesToIds = (node.evolves_to ?? []).map((n) =>
        Number(n.species.url.split("/").filter(Boolean).pop()),
      );
    }
    for (const child of node.evolves_to ?? []) {
      walkChain(child, stage + 1);
    }
  }
  for (const chain of chainsByUrl.values()) walkChain(chain as ChainNode, 1);

  // 6) finalize
  for (const e of map.values()) {
    e.isFullyEvolved = e.evolvesToIds.length === 0;
  }

  const all = [...map.values()]
    .sort((a, b) => a.id - b.id)
    .filter((e) => e.types.length > 0)
    .map(({ evolutionChainUrl: _u, ...rest }) => rest);

  const body = `// AUTO-GENERATED by scripts/build-pokemon.ts. Do not edit.
export type PokeType =
  | "normal" | "fire" | "water" | "electric" | "grass" | "ice"
  | "fighting" | "poison" | "ground" | "flying" | "psychic"
  | "bug" | "rock" | "ghost" | "dragon" | "dark" | "steel" | "fairy";

export interface PokeEntry {
  id: number;
  slug: string;
  name: string;
  types: PokeType[];
  evolvesFromId: number | null;
  evolvesToIds: number[];
  evolutionStage: 1 | 2 | 3;
  isFullyEvolved: boolean;
}

export const ALL_POKEMON: PokeEntry[] = ${JSON.stringify(all, null, 2)} as PokeEntry[];
`;
  writeFileSync("src/lib/pokemon-data.generated.ts", body);
  console.log(`wrote ${all.length} pokemon`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
