// One-shot script: scrape Bulbagarden trainer sprite categories.
// Run with: bun scripts/build-trainers.ts
import { writeFileSync } from "node:fs";

const CATEGORIES: { url: string; gen: 3 | 4 | 5 | "masters" }[] = [
  { url: "https://archives.bulbagarden.net/wiki/Category:Generation_III_Trainer_sprites", gen: 3 },
  { url: "https://archives.bulbagarden.net/wiki/Category:Generation_IV_Trainer_sprites", gen: 4 },
  { url: "https://archives.bulbagarden.net/wiki/Category:Generation_V_Trainer_sprites", gen: 5 },
  { url: "https://archives.bulbagarden.net/wiki/Category:Pok%C3%A9mon_Masters_Trainer_sprites", gen: "masters" },
];

interface Sprite { id: string; name: string; url: string; gen: 3 | 4 | 5 | "masters"; }

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/\.png$/i, "")
    .replace(/^spr[\s_]+/i, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function prettify(name: string): string {
  return name
    .replace(/\.png$/i, "")
    .replace(/^Spr[\s_]+/i, "")
    .replace(/_/g, " ")
    .trim();
}

async function fetchPage(url: string): Promise<{ html: string }> {
  const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0 trainer-roster-builder" } });
  return { html: await res.text() };
}

async function scrapeCategory(startUrl: string, gen: 3 | 4 | 5 | "masters"): Promise<Sprite[]> {
  const out: Sprite[] = [];
  const seen = new Set<string>();
  let url: string | null = startUrl;
  let page = 0;
  while (url && page < 20) {
    const { html } = await fetchPage(url);
    // Extract gallery image src + filename
    const re = /<img alt="" src="(https:\/\/archives\.bulbagarden\.net\/media\/upload\/[^"]+\.png)"[^>]*>[\s\S]*?title="File:([^"]+\.png)"/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(html))) {
      const fullUrl = m[1].replace("/media/upload/thumb/", "/media/upload/").replace(/\/\d+px-[^/]+$/, "");
      const filename = m[2];
      const id = slugify(filename);
      if (seen.has(id)) continue;
      seen.add(id);
      out.push({ id, name: prettify(filename), url: fullUrl, gen });
    }
    // next page link
    const nextMatch = html.match(/<a href="([^"]+)"[^>]*>next page<\/a>/i);
    url = nextMatch ? nextMatch[1].replace(/&amp;/g, "&") : null;
    if (url && url.startsWith("/")) url = `https://archives.bulbagarden.net${url}`;
    page++;
    console.log(`  ${gen} page ${page}: ${out.length} sprites total`);
  }
  return out;
}

async function main() {
  const all: Sprite[] = [];
  for (const c of CATEGORIES) {
    console.log(`Scraping ${c.gen}...`);
    const items = await scrapeCategory(c.url, c.gen);
    all.push(...items);
  }
  // dedupe across categories by id; keep the first occurrence
  const dedup = new Map<string, Sprite>();
  for (const s of all) if (!dedup.has(s.id)) dedup.set(s.id, s);
  const list = [...dedup.values()];

  const body =
`// AUTO-GENERATED by scripts/build-trainers.ts. Do not edit.
export interface TrainerSprite {
  id: string;
  name: string;
  url: string;
  gen: 3 | 4 | 5 | "masters";
}
const _DATA: TrainerSprite[] = (${JSON.stringify(list, null, 2)} as any);
export const TRAINER_SPRITES = _DATA;
`;
  writeFileSync("src/lib/trainer-data.generated.ts", body);
  console.log(`wrote ${list.length} trainers`);
}
  writeFileSync("src/lib/trainer-data.generated.ts", body);
  console.log(`wrote ${list.length} trainers`);
}

main().catch(e => { console.error(e); process.exit(1); });
