/**
 * Generates src/content/abilities/rolled/*.ts — one RolledAbilityDef file per
 * base (non-legendary) ability, mechanically emitted from the live
 * ABILITY_SETS table in src/lib/abilities.ts so the ported data can't drift
 * from what players actually roll.
 *
 * Run: npx vite-node -c scripts/balance-sim/vite.config.ts scripts/gen-rolled-content.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { ABILITY_SETS } from "../src/lib/abilities";
import type { PokeType } from "../src/lib/pokemon-data";

const OUT_DIR = "src/content/abilities/rolled";
mkdirSync(OUT_DIR, { recursive: true });

// A handful of ability ids collide with reserved words as bare module-level
// bindings ("static" — a StrictMode FutureReservedWord at that position).
const RESERVED_WORD_SUFFIX = new Set(["static"]);

const toIdentifier = (id: string) => {
  const camel = id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  return RESERVED_WORD_SUFFIX.has(camel) ? `${camel}Ability` : camel;
};

const entries: { identifier: string; id: string; type: PokeType }[] = [];

for (const [type, set] of Object.entries(ABILITY_SETS) as [PokeType, typeof ABILITY_SETS[PokeType]][]) {
  set.forEach((ability, slot) => {
    const identifier = toIdentifier(ability.id);
    entries.push({ identifier, id: ability.id, type });

    const body = `// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const ${identifier}: RolledAbilityDef = {
  id: "${ability.id}",
  name: ${JSON.stringify(ability.name)},
  type: "${ability.type}",
  description: ${JSON.stringify(ability.description)},
  slot: ${slot as 0 | 1 | 2},
};
`;
    writeFileSync(`${OUT_DIR}/${ability.id}.ts`, body);
  });
}

const typeOrder = Object.keys(ABILITY_SETS);
const indexBody = `// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";
import type { PokeType } from "../../../lib/pokemon-data";
${entries.map((e) => `import { ${e.identifier} } from "./${e.id}";`).join("\n")}

export type { RolledAbilityDef, AbilityId } from "./rolled-def";

export const ROLLED_LIST: readonly RolledAbilityDef[] = [
${entries.map((e) => `  ${e.identifier},`).join("\n")}
];

export const ROLLED_BY_ID: Record<string, RolledAbilityDef> = {
${entries.map((e) => `  ${JSON.stringify(e.id)}: ${e.identifier},`).join("\n")}
};

export const ROLLED_SETS: Record<PokeType, [RolledAbilityDef, RolledAbilityDef, RolledAbilityDef]> = {
${typeOrder
  .map((type) => {
    const three = entries.filter((e) => e.type === type);
    return `  ${type}: [${three.map((e) => e.identifier).join(", ")}],`;
  })
  .join("\n")}
};
`;
writeFileSync(`${OUT_DIR}/index.ts`, indexBody);

console.log(`Generated ${entries.length} rolled-ability content files + index.ts`);
