/**
 * Generates src/content/abilities/signature/*.ts — one thin wrapper file per
 * legendary/mythical row, from the live SIGNATURE_ABILITIES catalog.
 *
 * CLAUDE.md standing rule: nothing in content/abilities/signature/ is authored
 * by hand. These files exist only to give each row its own file per the
 * architecture doc's directory map; the catalog in src/lib/signature-abilities.ts
 * stays the single source of truth (it's still load-bearing for the legacy
 * `trigger`/`effect` wiring the live PvP RPCs use until Phase 5 retires it).
 *
 * Run: npx vite-node scripts/gen-signature-content.ts
 * Then: verify liveness.ts + balance-sim byte-identical before committing.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { ALL_LEGENDARY_MYTHICAL_IDS } from "../src/lib/legendary-data";
import { SIGNATURE_ABILITIES } from "../src/lib/signature-abilities";
import { findPokemon } from "../src/lib/pokemon-data";

const OUT_DIR = "src/content/abilities/signature";
mkdirSync(OUT_DIR, { recursive: true });

const toFileSlug = (internalKey: string) => internalKey.replace(/_/g, "-");
const toIdentifier = (internalKey: string) =>
  internalKey.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const entries: { identifier: string; fileSlug: string; internalKey: string }[] = [];

for (const pokemonId of ALL_LEGENDARY_MYTHICAL_IDS) {
  const row = SIGNATURE_ABILITIES[pokemonId];
  if (!row) throw new Error(`No SIGNATURE_ABILITIES row for roster id ${pokemonId}`);
  if (!row.engine) throw new Error(`Row ${pokemonId} (${row.internalKey}) has no engine spec`);

  const species = findPokemon(pokemonId)?.name;
  if (!species) throw new Error(`No species name for pokemonId ${pokemonId}`);

  const identifier = toIdentifier(row.internalKey);
  const fileSlug = toFileSlug(row.internalKey);
  entries.push({ identifier, fileSlug, internalKey: row.internalKey });

  const body = `// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[${pokemonId}] ("${species}") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[${pokemonId}];

export const ${identifier}: SignatureDef = {
  id: "${row.internalKey}",
  pokemonId: ${pokemonId},
  species: "${species.replace(/"/g, '\\"')}",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
`;
  writeFileSync(`${OUT_DIR}/${fileSlug}.ts`, body);
}

entries.sort((a, b) => a.fileSlug.localeCompare(b.fileSlug));

const indexBody = `// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
import type { SignatureDef } from "./signature-def";
${entries.map((e) => `import { ${e.identifier} } from "./${e.fileSlug}";`).join("\n")}

export type { SignatureDef } from "./signature-def";

export const SIGNATURE_LIST: readonly SignatureDef[] = [
${entries.map((e) => `  ${e.identifier},`).join("\n")}
];

export const SIGNATURE_BY_ID: Record<string, SignatureDef> = {
${entries.map((e) => `  ${JSON.stringify(e.internalKey)}: ${e.identifier},`).join("\n")}
};

export const SIGNATURE_BY_POKEMON_ID: Record<number, SignatureDef> = Object.fromEntries(
  SIGNATURE_LIST.map((d) => [d.pokemonId, d]),
);
`;
writeFileSync(`${OUT_DIR}/index.ts`, indexBody);

console.log(`Generated ${entries.length} signature content files + index.ts`);
