/**
 * Generates src/content/abilities/type/*.ts — one thin wrapper file per base
 * ability's Nearby-Battle (PvP) wiring, from the live TABLE in
 * src/lib/pvp-type-abilities.ts.
 *
 * These entries are executable behavior (damage tweaks, timing predicates),
 * not declarative data, so — same reasoning as content/abilities/signature/ —
 * the generated files wrap the existing TABLE entry by reference rather than
 * reimplementing it. lib/pvp-type-abilities.ts stays the single source of
 * truth for the actual logic.
 *
 * Run: npx vite-node -c scripts/balance-sim/vite.config.ts scripts/gen-type-content.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { TABLE } from "../src/lib/pvp-type-abilities";
import { ROLLED_LIST } from "../src/content/abilities/rolled";

const OUT_DIR = "src/content/abilities/type";
mkdirSync(OUT_DIR, { recursive: true });

const toIdentifier = (id: string) => {
  const camel = id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  return camel === "static" ? "staticAbility" : camel;
};

// Same 54 ids as content/abilities/rolled, in that registry's order.
const ids = ROLLED_LIST.map((a) => a.id);

for (const id of ids) {
  if (!(id in TABLE)) throw new Error(`No TABLE entry for ability id ${id}`);
  const identifier = toIdentifier(id);

  const body = `// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
// Wraps TABLE["${id}"] from lib/pvp-type-abilities.ts by reference; the
// behavior itself is authored there, not here.
import type { TypeAbilityDef } from "./type-def";
import { TABLE } from "../../../lib/pvp-type-abilities";

export const ${identifier}: TypeAbilityDef = {
  id: "${id}",
  pvp: TABLE["${id}"],
};
`;
  writeFileSync(`${OUT_DIR}/${id}.ts`, body);
}

const indexBody = `// GENERATED by scripts/gen-type-content.ts — do not hand-edit.
import type { TypeAbilityDef } from "./type-def";
import type { AbilityId } from "../rolled/rolled-def";
${ids.map((id) => `import { ${toIdentifier(id)} } from "./${id}";`).join("\n")}

export type { TypeAbilityDef } from "./type-def";

export const TYPE_ABILITY_LIST: readonly TypeAbilityDef[] = [
${ids.map((id) => `  ${toIdentifier(id)},`).join("\n")}
];

export const TYPE_ABILITY_BY_ID: Record<AbilityId, TypeAbilityDef> = {
${ids.map((id) => `  ${JSON.stringify(id)}: ${toIdentifier(id)},`).join("\n")}
};
`;
writeFileSync(`${OUT_DIR}/index.ts`, indexBody);

console.log(`Generated ${ids.length} type-ability content files + index.ts`);
