/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleIndexRouteImport } from './routes/battle.index'
import { Route as ApiTriviaRouteImport } from './routes/api.trivia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIndexRoute = BattleIndexRouteImport.update({
  id: '/battle/',
  path: '/battle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriviaRoute = ApiTriviaRouteImport.update({
  id: '/api/trivia',
  path: '/api/trivia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/trivia': typeof ApiTriviaRoute
  '/battle/': typeof BattleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/trivia': typeof ApiTriviaRoute
  '/battle': typeof BattleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/trivia': typeof ApiTriviaRoute
  '/battle/': typeof BattleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/trivia' | '/battle/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/trivia' | '/battle'
  id: '__root__' | '/' | '/api/trivia' | '/battle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTriviaRoute: typeof ApiTriviaRoute
  BattleIndexRoute: typeof BattleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/': {
      id: '/battle/'
      path: '/battle'
      fullPath: '/battle/'
      preLoaderRoute: typeof BattleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trivia': {
      id: '/api/trivia'
      path: '/api/trivia'
      fullPath: '/api/trivia'
      preLoaderRoute: typeof ApiTriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTriviaRoute: ApiTriviaRoute,
  BattleIndexRoute: BattleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
