// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      app_config: {
        Row: {
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string
          value?: Json
        }
        Update: {
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      chat_banned_words: {
        Row: {
          created_at: string
          word: string
        }
        Insert: {
          created_at?: string
          word: string
        }
        Update: {
          created_at?: string
          word?: string
        }
        Relationships: []
      }
      curated_questions: {
        Row: {
          category: string
          correct_index: number
          created_at: string
          created_by: string | null
          difficulty: string
          explanation: string
          id: string
          options: Json
          question: string
          times_correct: number
          times_served: number
          type_theme: string | null
          verified: boolean
        }
        Insert: {
          category: string
          correct_index: number
          created_at?: string
          created_by?: string | null
          difficulty: string
          explanation: string
          id?: string
          options: Json
          question: string
          times_correct?: number
          times_served?: number
          type_theme?: string | null
          verified?: boolean
        }
        Update: {
          category?: string
          correct_index?: number
          created_at?: string
          created_by?: string | null
          difficulty?: string
          explanation?: string
          id?: string
          options?: Json
          question?: string
          times_correct?: number
          times_served?: number
          type_theme?: string | null
          verified?: boolean
        }
        Relationships: []
      }
      daily_questions: {
        Row: {
          created_at: string
          date: string
          questions: Json
          served_ids: string[]
        }
        Insert: {
          created_at?: string
          date: string
          questions: Json
          served_ids?: string[]
        }
        Update: {
          created_at?: string
          date?: string
          questions?: Json
          served_ids?: string[]
        }
        Relationships: []
      }
      daily_runs: {
        Row: {
          correct: number
          created_at: string
          date: string
          id: string
          time_ms: number
          total: number
          user_id: string
        }
        Insert: {
          correct: number
          created_at?: string
          date: string
          id?: string
          time_ms: number
          total: number
          user_id: string
        }
        Update: {
          correct?: number
          created_at?: string
          date?: string
          id?: string
          time_ms?: number
          total?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_runs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      feedback: {
        Row: {
          app_version: string | null
          category: string
          contact: string | null
          created_at: string
          id: string
          message: string
          trainer_name: string | null
          user_id: string
        }
        Insert: {
          app_version?: string | null
          category: string
          contact?: string | null
          created_at?: string
          id?: string
          message: string
          trainer_name?: string | null
          user_id?: string
        }
        Update: {
          app_version?: string | null
          category?: string
          contact?: string | null
          created_at?: string
          id?: string
          message?: string
          trainer_name?: string | null
          user_id?: string
        }
        Relationships: []
      }
      friend_requests: {
        Row: {
          created_at: string
          from_id: string
          id: string
          responded_at: string | null
          status: string
          to_id: string
        }
        Insert: {
          created_at?: string
          from_id: string
          id?: string
          responded_at?: string | null
          status?: string
          to_id: string
        }
        Update: {
          created_at?: string
          from_id?: string
          id?: string
          responded_at?: string | null
          status?: string
          to_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "friend_requests_from_id_fkey"
            columns: ["from_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friend_requests_to_id_fkey"
            columns: ["to_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      friends: {
        Row: {
          created_at: string
          friend_id: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          friend_id: string
          owner_id: string
        }
        Update: {
          created_at?: string
          friend_id?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "friends_friend_id_fkey"
            columns: ["friend_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      grants: {
        Row: {
          granted_at: string
          kind: string
          ref_id: string
          user_id: string
        }
        Insert: {
          granted_at?: string
          kind: string
          ref_id: string
          user_id: string
        }
        Update: {
          granted_at?: string
          kind?: string
          ref_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "grants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      mega_attempts: {
        Row: {
          created_at: string
          event_id: string
          id: string
          log: Json
          status: string
          total: number
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          id?: string
          log?: Json
          status?: string
          total: number
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          id?: string
          log?: Json
          status?: string
          total?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mega_attempts_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "mega_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mega_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      mega_event_questions: {
        Row: {
          event_id: string
          generated_at: string
          questions: Json
        }
        Insert: {
          event_id: string
          generated_at?: string
          questions: Json
        }
        Update: {
          event_id?: string
          generated_at?: string
          questions?: Json
        }
        Relationships: [
          {
            foreignKeyName: "mega_event_questions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: true
            referencedRelation: "mega_events"
            referencedColumns: ["id"]
          },
        ]
      }
      mega_events: {
        Row: {
          base_dex_id: number
          base_name: string
          champ_items: number
          champ_tp: number
          champ_xp: number
          created_at: string
          ends_at: string
          id: string
          mega_id: number
          name: string
          starts_at: string
          trophy_id: string
          trophy_name: string
          types: string[]
          win_items: number
          win_tp: number
          win_xp: number
        }
        Insert: {
          base_dex_id: number
          base_name: string
          champ_items?: number
          champ_tp?: number
          champ_xp?: number
          created_at?: string
          ends_at: string
          id: string
          mega_id: number
          name: string
          starts_at: string
          trophy_id: string
          trophy_name: string
          types: string[]
          win_items?: number
          win_tp?: number
          win_xp?: number
        }
        Update: {
          base_dex_id?: number
          base_name?: string
          champ_items?: number
          champ_tp?: number
          champ_xp?: number
          created_at?: string
          ends_at?: string
          id?: string
          mega_id?: number
          name?: string
          starts_at?: string
          trophy_id?: string
          trophy_name?: string
          types?: string[]
          win_items?: number
          win_tp?: number
          win_xp?: number
        }
        Relationships: []
      }
      mega_runs: {
        Row: {
          accuracy: number
          attempts: number
          correct: number
          event_id: string
          finished_at: string
          id: string
          level: number
          time_ms: number
          total: number
          trainer_name: string
          trainer_sprite: string
          user_id: string
        }
        Insert: {
          accuracy: number
          attempts?: number
          correct: number
          event_id: string
          finished_at?: string
          id?: string
          level: number
          time_ms: number
          total: number
          trainer_name: string
          trainer_sprite: string
          user_id: string
        }
        Update: {
          accuracy?: number
          attempts?: number
          correct?: number
          event_id?: string
          finished_at?: string
          id?: string
          level?: number
          time_ms?: number
          total?: number
          trainer_name?: string
          trainer_sprite?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mega_runs_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "mega_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mega_runs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          ace_pokemon_id: number | null
          created_at: string
          friend_code: string
          id: string
          last_daily_claim: string | null
          last_gift_claim: string | null
          last_mega_played: string | null
          last_reminder_sent: string | null
          last_weekly_attempt: string | null
          last_whos_that_played: string | null
          level: number
          pokedex_count: number
          trainer_name: string | null
          trainer_sprite: string
          updated_at: string
          xp: number
        }
        Insert: {
          ace_pokemon_id?: number | null
          created_at?: string
          friend_code: string
          id: string
          last_daily_claim?: string | null
          last_gift_claim?: string | null
          last_mega_played?: string | null
          last_reminder_sent?: string | null
          last_weekly_attempt?: string | null
          last_whos_that_played?: string | null
          level?: number
          pokedex_count?: number
          trainer_name?: string | null
          trainer_sprite?: string
          updated_at?: string
          xp?: number
        }
        Update: {
          ace_pokemon_id?: number | null
          created_at?: string
          friend_code?: string
          id?: string
          last_daily_claim?: string | null
          last_gift_claim?: string | null
          last_mega_played?: string | null
          last_reminder_sent?: string | null
          last_weekly_attempt?: string | null
          last_whos_that_played?: string | null
          level?: number
          pokedex_count?: number
          trainer_name?: string | null
          trainer_sprite?: string
          updated_at?: string
          xp?: number
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          user_id?: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          user_id?: string
        }
        Relationships: []
      }
      pvp_chat_bans: {
        Row: {
          banned_by: string | null
          created_at: string
          expires_at: string | null
          reason: string | null
          user_id: string
        }
        Insert: {
          banned_by?: string | null
          created_at?: string
          expires_at?: string | null
          reason?: string | null
          user_id: string
        }
        Update: {
          banned_by?: string | null
          created_at?: string
          expires_at?: string | null
          reason?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pvp_chat_bans_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_chat_messages: {
        Row: {
          body: string
          created_at: string
          id: string
          match_id: string
          trainer_name: string
          trainer_sprite: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          match_id: string
          trainer_name: string
          trainer_sprite: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          match_id?: string
          trainer_name?: string
          trainer_sprite?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pvp_chat_messages_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "pvp_live_matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_chat_messages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_chat_reports: {
        Row: {
          created_at: string
          id: string
          message_id: string
          reason: string | null
          reporter_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          message_id: string
          reason?: string | null
          reporter_id: string
        }
        Update: {
          created_at?: string
          id?: string
          message_id?: string
          reason?: string | null
          reporter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pvp_chat_reports_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "pvp_chat_messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_chat_reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_item_effects: {
        Row: {
          item_id: string
          kind: string
          payload: Json
          target: string
        }
        Insert: {
          item_id: string
          kind: string
          payload: Json
          target: string
        }
        Update: {
          item_id?: string
          kind?: string
          payload?: Json
          target?: string
        }
        Relationships: []
      }
      pvp_live_answer_shadow_log: {
        Row: {
          client_report: Json
          created_at: string
          id: number
          match_id: string
          question_index: number
          runtime_snapshot: Json
          side: string
          verified_correct: boolean
        }
        Insert: {
          client_report: Json
          created_at?: string
          id?: never
          match_id: string
          question_index: number
          runtime_snapshot: Json
          side: string
          verified_correct: boolean
        }
        Update: {
          client_report?: Json
          created_at?: string
          id?: never
          match_id?: string
          question_index?: number
          runtime_snapshot?: Json
          side?: string
          verified_correct?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "pvp_live_answer_shadow_log_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "pvp_live_matches"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_live_effects: {
        Row: {
          created_at: string
          id: string
          item_id: string | null
          kind: string
          match_id: string
          payload: Json
          pokemon_id: number | null
          question_index: number
          source: string
          source_id: string
          target: string
        }
        Insert: {
          created_at?: string
          id?: string
          item_id?: string | null
          kind: string
          match_id: string
          payload?: Json
          pokemon_id?: number | null
          question_index: number
          source?: string
          source_id: string
          target: string
        }
        Update: {
          created_at?: string
          id?: string
          item_id?: string | null
          kind?: string
          match_id?: string
          payload?: Json
          pokemon_id?: number | null
          question_index?: number
          source?: string
          source_id?: string
          target?: string
        }
        Relationships: [
          {
            foreignKeyName: "pvp_live_effects_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "pvp_live_matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_live_effects_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_live_matches: {
        Row: {
          created_at: string
          expires_at: string
          guest_ability_id: string | null
          guest_ability_started: boolean
          guest_answered_live: number
          guest_bot_profile: Json | null
          guest_completed_at: string | null
          guest_confused_ticks_live: number
          guest_correct: number | null
          guest_correct_live: number
          guest_had_wrong: boolean
          guest_hp: number
          guest_id: string
          guest_items_used: number
          guest_last_submitted_idx: number
          guest_manual_fires: number
          guest_moxie_stacks: number
          guest_partner_id: number | null
          guest_post_answer_last_idx: number
          guest_prev_answer_elapsed_ms: number
          guest_prev_correct: boolean
          guest_revive_bonus_until: number
          guest_revived: boolean
          guest_score: number | null
          guest_sig_engine_last_idx: number
          guest_sig_latched: boolean
          guest_sig_runtime: Json
          guest_sig_state: Json
          guest_stages: Json
          guest_statuses: Json
          guest_streak: number | null
          guest_streak_live: number
          guest_sturdy_used: boolean
          guest_suppressed_until: number
          guest_sword_of_ruin_charges: number
          guest_time_ms: number | null
          guest_time_ms_live: number
          guest_total: number | null
          guest_transform_id: number | null
          guest_type_ability_started: boolean
          guest_used_healing: boolean
          guest_wrong_count: number
          guest_wrong_streak_live: number
          host_ability_id: string | null
          host_ability_started: boolean
          host_answered_live: number
          host_completed_at: string | null
          host_confused_ticks_live: number
          host_correct: number | null
          host_correct_live: number
          host_had_wrong: boolean
          host_hp: number
          host_id: string
          host_items_used: number
          host_last_submitted_idx: number
          host_manual_fires: number
          host_moxie_stacks: number
          host_partner_id: number | null
          host_post_answer_last_idx: number
          host_prev_answer_elapsed_ms: number
          host_prev_correct: boolean
          host_revive_bonus_until: number
          host_revived: boolean
          host_score: number | null
          host_sig_engine_last_idx: number
          host_sig_latched: boolean
          host_sig_runtime: Json
          host_sig_state: Json
          host_stages: Json
          host_statuses: Json
          host_streak: number | null
          host_streak_live: number
          host_sturdy_used: boolean
          host_suppressed_until: number
          host_sword_of_ruin_charges: number
          host_time_ms: number | null
          host_time_ms_live: number
          host_total: number | null
          host_transform_id: number | null
          host_type_ability_started: boolean
          host_used_healing: boolean
          host_wrong_count: number
          host_wrong_streak_live: number
          id: string
          is_bot_match: boolean
          live_resolved_at: string | null
          questions: Json
          rev: number
          started_at: string
          status: string
          weather_owner: string | null
          winner_id: string | null
        }
        Insert: {
          created_at?: string
          expires_at?: string
          guest_ability_id?: string | null
          guest_ability_started?: boolean
          guest_answered_live?: number
          guest_bot_profile?: Json | null
          guest_completed_at?: string | null
          guest_confused_ticks_live?: number
          guest_correct?: number | null
          guest_correct_live?: number
          guest_had_wrong?: boolean
          guest_hp?: number
          guest_id: string
          guest_items_used?: number
          guest_last_submitted_idx?: number
          guest_manual_fires?: number
          guest_moxie_stacks?: number
          guest_partner_id?: number | null
          guest_post_answer_last_idx?: number
          guest_prev_answer_elapsed_ms?: number
          guest_prev_correct?: boolean
          guest_revive_bonus_until?: number
          guest_revived?: boolean
          guest_score?: number | null
          guest_sig_engine_last_idx?: number
          guest_sig_latched?: boolean
          guest_sig_runtime?: Json
          guest_sig_state?: Json
          guest_stages?: Json
          guest_statuses?: Json
          guest_streak?: number | null
          guest_streak_live?: number
          guest_sturdy_used?: boolean
          guest_suppressed_until?: number
          guest_sword_of_ruin_charges?: number
          guest_time_ms?: number | null
          guest_time_ms_live?: number
          guest_total?: number | null
          guest_transform_id?: number | null
          guest_type_ability_started?: boolean
          guest_used_healing?: boolean
          guest_wrong_count?: number
          guest_wrong_streak_live?: number
          host_ability_id?: string | null
          host_ability_started?: boolean
          host_answered_live?: number
          host_completed_at?: string | null
          host_confused_ticks_live?: number
          host_correct?: number | null
          host_correct_live?: number
          host_had_wrong?: boolean
          host_hp?: number
          host_id: string
          host_items_used?: number
          host_last_submitted_idx?: number
          host_manual_fires?: number
          host_moxie_stacks?: number
          host_partner_id?: number | null
          host_post_answer_last_idx?: number
          host_prev_answer_elapsed_ms?: number
          host_prev_correct?: boolean
          host_revive_bonus_until?: number
          host_revived?: boolean
          host_score?: number | null
          host_sig_engine_last_idx?: number
          host_sig_latched?: boolean
          host_sig_runtime?: Json
          host_sig_state?: Json
          host_stages?: Json
          host_statuses?: Json
          host_streak?: number | null
          host_streak_live?: number
          host_sturdy_used?: boolean
          host_suppressed_until?: number
          host_sword_of_ruin_charges?: number
          host_time_ms?: number | null
          host_time_ms_live?: number
          host_total?: number | null
          host_transform_id?: number | null
          host_type_ability_started?: boolean
          host_used_healing?: boolean
          host_wrong_count?: number
          host_wrong_streak_live?: number
          id?: string
          is_bot_match?: boolean
          live_resolved_at?: string | null
          questions: Json
          rev?: number
          started_at: string
          status?: string
          weather_owner?: string | null
          winner_id?: string | null
        }
        Update: {
          created_at?: string
          expires_at?: string
          guest_ability_id?: string | null
          guest_ability_started?: boolean
          guest_answered_live?: number
          guest_bot_profile?: Json | null
          guest_completed_at?: string | null
          guest_confused_ticks_live?: number
          guest_correct?: number | null
          guest_correct_live?: number
          guest_had_wrong?: boolean
          guest_hp?: number
          guest_id?: string
          guest_items_used?: number
          guest_last_submitted_idx?: number
          guest_manual_fires?: number
          guest_moxie_stacks?: number
          guest_partner_id?: number | null
          guest_post_answer_last_idx?: number
          guest_prev_answer_elapsed_ms?: number
          guest_prev_correct?: boolean
          guest_revive_bonus_until?: number
          guest_revived?: boolean
          guest_score?: number | null
          guest_sig_engine_last_idx?: number
          guest_sig_latched?: boolean
          guest_sig_runtime?: Json
          guest_sig_state?: Json
          guest_stages?: Json
          guest_statuses?: Json
          guest_streak?: number | null
          guest_streak_live?: number
          guest_sturdy_used?: boolean
          guest_suppressed_until?: number
          guest_sword_of_ruin_charges?: number
          guest_time_ms?: number | null
          guest_time_ms_live?: number
          guest_total?: number | null
          guest_transform_id?: number | null
          guest_type_ability_started?: boolean
          guest_used_healing?: boolean
          guest_wrong_count?: number
          guest_wrong_streak_live?: number
          host_ability_id?: string | null
          host_ability_started?: boolean
          host_answered_live?: number
          host_completed_at?: string | null
          host_confused_ticks_live?: number
          host_correct?: number | null
          host_correct_live?: number
          host_had_wrong?: boolean
          host_hp?: number
          host_id?: string
          host_items_used?: number
          host_last_submitted_idx?: number
          host_manual_fires?: number
          host_moxie_stacks?: number
          host_partner_id?: number | null
          host_post_answer_last_idx?: number
          host_prev_answer_elapsed_ms?: number
          host_prev_correct?: boolean
          host_revive_bonus_until?: number
          host_revived?: boolean
          host_score?: number | null
          host_sig_engine_last_idx?: number
          host_sig_latched?: boolean
          host_sig_runtime?: Json
          host_sig_state?: Json
          host_stages?: Json
          host_statuses?: Json
          host_streak?: number | null
          host_streak_live?: number
          host_sturdy_used?: boolean
          host_suppressed_until?: number
          host_sword_of_ruin_charges?: number
          host_time_ms?: number | null
          host_time_ms_live?: number
          host_total?: number | null
          host_transform_id?: number | null
          host_type_ability_started?: boolean
          host_used_healing?: boolean
          host_wrong_count?: number
          host_wrong_streak_live?: number
          id?: string
          is_bot_match?: boolean
          live_resolved_at?: string | null
          questions?: Json
          rev?: number
          started_at?: string
          status?: string
          weather_owner?: string | null
          winner_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pvp_live_matches_guest_id_fkey"
            columns: ["guest_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_live_matches_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_live_matches_winner_id_fkey"
            columns: ["winner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_matches: {
        Row: {
          challenger_completed_at: string | null
          challenger_correct: number | null
          challenger_id: string
          challenger_score: number | null
          challenger_streak: number | null
          challenger_time_ms: number | null
          challenger_total: number | null
          created_at: string
          expires_at: string
          id: string
          opponent_completed_at: string | null
          opponent_correct: number | null
          opponent_id: string
          opponent_score: number | null
          opponent_streak: number | null
          opponent_time_ms: number | null
          opponent_total: number | null
          questions: Json
          status: string
          winner_id: string | null
        }
        Insert: {
          challenger_completed_at?: string | null
          challenger_correct?: number | null
          challenger_id: string
          challenger_score?: number | null
          challenger_streak?: number | null
          challenger_time_ms?: number | null
          challenger_total?: number | null
          created_at?: string
          expires_at?: string
          id?: string
          opponent_completed_at?: string | null
          opponent_correct?: number | null
          opponent_id: string
          opponent_score?: number | null
          opponent_streak?: number | null
          opponent_time_ms?: number | null
          opponent_total?: number | null
          questions: Json
          status?: string
          winner_id?: string | null
        }
        Update: {
          challenger_completed_at?: string | null
          challenger_correct?: number | null
          challenger_id?: string
          challenger_score?: number | null
          challenger_streak?: number | null
          challenger_time_ms?: number | null
          challenger_total?: number | null
          created_at?: string
          expires_at?: string
          id?: string
          opponent_completed_at?: string | null
          opponent_correct?: number | null
          opponent_id?: string
          opponent_score?: number | null
          opponent_streak?: number | null
          opponent_time_ms?: number | null
          opponent_total?: number | null
          questions?: Json
          status?: string
          winner_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pvp_matches_challenger_id_fkey"
            columns: ["challenger_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_matches_opponent_id_fkey"
            columns: ["opponent_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pvp_matches_winner_id_fkey"
            columns: ["winner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pvp_signature_effects: {
        Row: {
          effect_index: number
          kind: string
          payload: Json
          phase: string
          pokemon_id: number
          target: string
        }
        Insert: {
          effect_index: number
          kind: string
          payload: Json
          phase: string
          pokemon_id: number
          target: string
        }
        Update: {
          effect_index?: number
          kind?: string
          payload?: Json
          phase?: string
          pokemon_id?: number
          target?: string
        }
        Relationships: []
      }
      pvp_type_ability_effects: {
        Row: {
          ability_id: string
          effect_index: number
          kind: string
          payload: Json
          phase: string
          target: string
        }
        Insert: {
          ability_id: string
          effect_index: number
          kind: string
          payload: Json
          phase: string
          target: string
        }
        Update: {
          ability_id?: string
          effect_index?: number
          kind?: string
          payload?: Json
          phase?: string
          target?: string
        }
        Relationships: []
      }
      referrals: {
        Row: {
          created_at: string
          id: string
          referred_id: string
          referrer_id: string
          referrer_reward_claimed: boolean
        }
        Insert: {
          created_at?: string
          id?: string
          referred_id: string
          referrer_id: string
          referrer_reward_claimed?: boolean
        }
        Update: {
          created_at?: string
          id?: string
          referred_id?: string
          referrer_id?: string
          referrer_reward_claimed?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "referrals_referred_id_fkey"
            columns: ["referred_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referrals_referrer_id_fkey"
            columns: ["referrer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      saves: {
        Row: {
          state: Json
          updated_at: string
          user_id: string
          version: number
        }
        Insert: {
          state: Json
          updated_at?: string
          user_id: string
          version?: number
        }
        Update: {
          state?: Json
          updated_at?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "saves_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      solo_battles: {
        Row: {
          cfg: Json
          created_at: string
          id: string
          log: Json
          result: Json | null
          seed: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          cfg: Json
          created_at?: string
          id?: string
          log?: Json
          result?: Json | null
          seed: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          cfg?: Json
          created_at?: string
          id?: string
          log?: Json
          result?: Json | null
          seed?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "solo_battles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      whos_that_rounds: {
        Row: {
          choices: Json
          correct: boolean | null
          created_at: string
          crop_back: boolean
          crop_dx: number
          crop_dy: number
          hour_key: number
          id: string
          is_shiny: boolean
          mode: string
          mon_id: number
          name: string
          resolved: boolean
          reward_icon: string
          reward_id: string
          reward_name: string
          types: Json
          user_id: string
        }
        Insert: {
          choices: Json
          correct?: boolean | null
          created_at?: string
          crop_back: boolean
          crop_dx: number
          crop_dy: number
          hour_key: number
          id?: string
          is_shiny: boolean
          mode: string
          mon_id: number
          name: string
          resolved?: boolean
          reward_icon: string
          reward_id: string
          reward_name: string
          types: Json
          user_id: string
        }
        Update: {
          choices?: Json
          correct?: boolean | null
          created_at?: string
          crop_back?: boolean
          crop_dx?: number
          crop_dy?: number
          hour_key?: number
          id?: string
          is_shiny?: boolean
          mode?: string
          mon_id?: number
          name?: string
          resolved?: boolean
          reward_icon?: string
          reward_id?: string
          reward_name?: string
          types?: Json
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "whos_that_rounds_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _pvp_apply_engine_status: {
        Args: {
          _i_am_host: boolean
          _match_id: string
          _pokemon_id: number
          _question_index: number
        }
        Returns: Json
      }
      _pvp_apply_m4_fx: {
        Args: {
          _i_am_host: boolean
          _match_id: string
          _pokemon_id: number
          _question_index: number
        }
        Returns: Json
      }
      _pvp_apply_status: {
        Args: { _cures: number; _kind: string; _statuses: Json }
        Returns: Json
      }
      _pvp_bump_stage: {
        Args: { _delta: number; _stages: Json; _stat: string }
        Returns: Json
      }
      _pvp_bump_stage_tracked: {
        Args: {
          _cap: number
          _dex: string
          _per_fire: number
          _runtime: Json
          _stages: Json
          _stat: string
          _target: string
        }
        Returns: Json
      }
      _pvp_cure_status: {
        Args: { _kind: string; _statuses: Json }
        Returns: Json
      }
      _pvp_index_shield_zero: {
        Args: { _dex: number; _q_no: number; _runtime: Json }
        Returns: boolean
      }
      _pvp_is_major_status: { Args: { _kind: string }; Returns: boolean }
      _pvp_m4_row_disabled: {
        Args: {
          _i_am_host: boolean
          _match: Database["public"]["Tables"]["pvp_live_matches"]["Row"]
          _pokemon_id: number
        }
        Returns: boolean
      }
      _pvp_m4_window_active: {
        Args: { _dex: number; _key: string; _q_no: number; _runtime: Json }
        Returns: boolean
      }
      _pvp_m4_window_apply: {
        Args: {
          _i_am_host: boolean
          _match_id: string
          _opp_timer_ms: number
          _opp_timer_questions: number
          _pokemon_id: number
          _question_index: number
          _self_dmg_zero: boolean
          _shield_questions: number
        }
        Returns: Json
      }
      _pvp_poison_tick: { Args: { _statuses: Json }; Returns: Json }
      _pvp_revert_ability_stat: {
        Args: {
          _dex: string
          _opp_stages: Json
          _runtime: Json
          _self_stages: Json
        }
        Returns: Json
      }
      _pvp_shield_pct: { Args: { _dex: number }; Returns: number }
      _pvp_sig_engine_apply: {
        Args: {
          _correct: boolean
          _disable_kind: string
          _disable_n: number
          _disable_next_question: boolean
          _expire_after_questions?: number
          _i_am_host: boolean
          _incorrect_stat_specs?: Json
          _match_id: string
          _opp_hp?: number
          _pokemon_id: number
          _question_index: number
          _self_hp?: number
          _stack_cap: number
          _stat_specs: Json
          _trigger_fired: boolean
        }
        Returns: Json
      }
      apply_bot_pvp_move_v2: {
        Args: {
          _caller_id: string
          _correct: boolean
          _dmg: number
          _match_id: string
          _next_state: Json
          _question_index: number
          _self_dmg: number
          _time_ms: number
        }
        Returns: Json
      }
      apply_bot_pvp_signature_effect: {
        Args: {
          _match_id: string
          _phase: string
          _pokemon_id: number
          _question_index: number
          _scale_count?: number
        }
        Returns: Json
      }
      apply_pvp_live_answer_v2: {
        Args: {
          _caller_id: string
          _confusion_missed: boolean
          _edge_dmg: number
          _edge_self_dmg: number
          _match_id: string
          _next_state: Json
          _question_index: number
          _selected_index: number
          _time_ms: number
        }
        Returns: Json
      }
      apply_pvp_signature_effect: {
        Args: {
          _match_id: string
          _phase: string
          _pokemon_id: number
          _question_index: number
          _scale_count?: number
        }
        Returns: Json
      }
      apply_pvp_type_ability_effect: {
        Args: {
          _ability_id: string
          _match_id: string
          _phase: string
          _question_index: number
        }
        Returns: Json
      }
      claim_pending_referral_rewards: { Args: never; Returns: Json }
      claim_referral: { Args: { _code: string }; Returns: Json }
      claim_trainer_name: { Args: { _name: string }; Returns: Json }
      create_pvp_challenge: {
        Args: { _opponent_id: string; _questions: Json }
        Returns: Json
      }
      decline_pvp_challenge: { Args: { _match_id: string }; Returns: Json }
      forfeit_live_pvp_match:
        | { Args: { _match_id: string }; Returns: Json }
        | { Args: { _concede?: boolean; _match_id: string }; Returns: Json }
      get_curated_questions: {
        Args: {
          p_count: number
          p_difficulties: string[]
          p_exclude?: string[]
          p_type_theme?: string
        }
        Returns: {
          category: string
          correct_index: number
          difficulty: string
          explanation: string
          id: string
          options: Json
          question: string
          type_theme: string
        }[]
      }
      get_mega_leaderboard: {
        Args: { p_event_id: string; p_limit?: number }
        Returns: {
          accuracy: number
          correct: number
          level: number
          time_ms: number
          total: number
          trainer_name: string
          trainer_sprite: string
          user_id: string
        }[]
      }
      get_mega_questions_public: { Args: { p_event_id: string }; Returns: Json }
      get_pvp_chat_state: { Args: { _match_id: string }; Returns: Json }
      increment_curated_correct: {
        Args: { question_id: string }
        Returns: undefined
      }
      increment_curated_served: {
        Args: { question_ids: string[] }
        Returns: undefined
      }
      insert_daily_if_absent: {
        Args: { p_date: string; p_questions: Json; p_served_ids?: string[] }
        Returns: undefined
      }
      insert_mega_questions_if_absent: {
        Args: { p_event_id: string; p_questions: Json }
        Returns: undefined
      }
      is_trainer_name_available: { Args: { _name: string }; Returns: boolean }
      list_incoming_friend_requests: {
        Args: never
        Returns: {
          created_at: string
          friend_code: string
          from_id: string
          level: number
          request_id: string
          trainer_name: string
          trainer_sprite: string
        }[]
      }
      list_pvp_invites: {
        Args: never
        Returns: {
          challenger_completed_at: string | null
          challenger_correct: number | null
          challenger_id: string
          challenger_score: number | null
          challenger_streak: number | null
          challenger_time_ms: number | null
          challenger_total: number | null
          created_at: string
          expires_at: string
          id: string
          opponent_completed_at: string | null
          opponent_correct: number | null
          opponent_id: string
          opponent_score: number | null
          opponent_streak: number | null
          opponent_time_ms: number | null
          opponent_total: number | null
          questions: Json
          status: string
          winner_id: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "pvp_matches"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      list_pvp_matches: {
        Args: never
        Returns: {
          challenger_completed_at: string | null
          challenger_correct: number | null
          challenger_id: string
          challenger_score: number | null
          challenger_streak: number | null
          challenger_time_ms: number | null
          challenger_total: number | null
          created_at: string
          expires_at: string
          id: string
          opponent_completed_at: string | null
          opponent_correct: number | null
          opponent_id: string
          opponent_score: number | null
          opponent_streak: number | null
          opponent_time_ms: number | null
          opponent_total: number | null
          questions: Json
          status: string
          winner_id: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "pvp_matches"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      lookup_profile_by_code: {
        Args: { _code: string }
        Returns: {
          ace_pokemon_id: number | null
          created_at: string
          friend_code: string
          id: string
          last_daily_claim: string | null
          last_gift_claim: string | null
          last_mega_played: string | null
          last_reminder_sent: string | null
          last_weekly_attempt: string | null
          last_whos_that_played: string | null
          level: number
          pokedex_count: number
          trainer_name: string | null
          trainer_sprite: string
          updated_at: string
          xp: number
        }
        SetofOptions: {
          from: "*"
          to: "profiles"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      my_pending_request_targets: { Args: never; Returns: string[] }
      pick_battle_curated: {
        Args: { p_count: number; p_difficulty: string; p_exclude?: string[] }
        Returns: {
          category: string
          correct_index: number
          explanation: string
          id: string
          options: Json
          question: string
        }[]
      }
      pick_daily_curated: {
        Args: { p_easy?: number; p_medium?: number; p_window?: number }
        Returns: {
          category: string
          correct_index: number
          explanation: string
          id: string
          options: Json
          question: string
        }[]
      }
      pvp_bot_sig_engine_status: {
        Args: {
          _match_id: string
          _pokemon_id: number
          _question_index: number
        }
        Returns: Json
      }
      pvp_bot_sig_engine_tick: {
        Args: {
          _correct: boolean
          _disable_kind?: string
          _disable_n?: number
          _disable_next_question?: boolean
          _expire_after_questions?: number
          _incorrect_stat_specs?: Json
          _match_id: string
          _opp_hp?: number
          _pokemon_id: number
          _question_index: number
          _self_hp?: number
          _stack_cap?: number
          _stat_specs?: Json
          _trigger_fired: boolean
        }
        Returns: Json
      }
      pvp_bot_sig_m4_fx: {
        Args: {
          _match_id: string
          _pokemon_id: number
          _question_index: number
        }
        Returns: Json
      }
      pvp_bot_sig_m4_window: {
        Args: {
          _match_id: string
          _opp_timer_ms?: number
          _opp_timer_questions?: number
          _pokemon_id: number
          _question_index: number
          _self_dmg_zero?: boolean
          _shield_questions?: number
        }
        Returns: Json
      }
      pvp_sig_engine_status: {
        Args: {
          _match_id: string
          _pokemon_id: number
          _question_index: number
        }
        Returns: Json
      }
      pvp_sig_engine_tick: {
        Args: {
          _correct: boolean
          _disable_kind?: string
          _disable_n?: number
          _disable_next_question?: boolean
          _expire_after_questions?: number
          _incorrect_stat_specs?: Json
          _match_id: string
          _opp_hp?: number
          _pokemon_id: number
          _question_index: number
          _self_hp?: number
          _stack_cap?: number
          _stat_specs?: Json
          _trigger_fired: boolean
        }
        Returns: Json
      }
      pvp_sig_m4_fx: {
        Args: {
          _match_id: string
          _pokemon_id: number
          _question_index: number
        }
        Returns: Json
      }
      pvp_sig_m4_window: {
        Args: {
          _match_id: string
          _opp_timer_ms?: number
          _opp_timer_questions?: number
          _pokemon_id: number
          _question_index: number
          _self_dmg_zero?: boolean
          _shield_questions?: number
        }
        Returns: Json
      }
      report_pvp_chat_message: {
        Args: { _message_id: string; _reason: string }
        Returns: Json
      }
      respond_friend_request: {
        Args: { _accept: boolean; _request_id: string }
        Returns: Json
      }
      reveal_mega_answer: {
        Args: { p_event_id: string; p_q_index: number }
        Returns: Json
      }
      send_friend_request: { Args: { _code: string }; Returns: Json }
      send_friend_request_by_id: { Args: { _target: string }; Returns: Json }
      send_pvp_chat_message: {
        Args: { _body: string; _match_id: string }
        Returns: Json
      }
      set_live_pvp_partner: {
        Args: { _ability_id?: string; _match_id: string; _partner_id: number }
        Returns: Json
      }
      set_live_pvp_transform: {
        Args: { _match_id: string; _transform_id: number }
        Returns: Json
      }
      start_bot_pvp_match: {
        Args: { _partner_id?: number; _questions: Json }
        Returns: Json
      }
      start_live_pvp_match: {
        Args: { _opponent_code: string; _partner_id?: number; _questions: Json }
        Returns: Json
      }
      submit_live_pvp_result: {
        Args: {
          _correct: number
          _match_id: string
          _max_streak: number
          _time_ms: number
          _total: number
        }
        Returns: Json
      }
      submit_mega_run: {
        Args: {
          p_accuracy: number
          p_correct: number
          p_event_id: string
          p_time_ms: number
          p_total: number
        }
        Returns: {
          accuracy: number
          attempts: number
          correct: number
          event_id: string
          finished_at: string
          id: string
          level: number
          time_ms: number
          total: number
          trainer_name: string
          trainer_sprite: string
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "mega_runs"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      submit_pvp_result: {
        Args: {
          _correct: number
          _match_id: string
          _max_streak: number
          _time_ms: number
          _total: number
        }
        Returns: Json
      }
      use_bot_pvp_live_item: {
        Args: { _item_id: string; _match_id: string; _question_index: number }
        Returns: Json
      }
      use_pvp_live_item: {
        Args: { _item_id: string; _match_id: string; _question_index: number }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
