// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[803] ("Poipole") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[803];

export const beastBoostPoipole: SignatureDef = {
  id: "beast_boost_poipole",
  pokemonId: 803,
  species: "Poipole",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
