// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[1008] ("Miraidon") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[1008];

export const electroDrift: SignatureDef = {
  id: "electro_drift",
  pokemonId: 1008,
  species: "Miraidon",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
