// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[379] ("Registeel") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[379];

export const flashCannonRegisteel: SignatureDef = {
  id: "flash_cannon_registeel",
  pokemonId: 379,
  species: "Registeel",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
