// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[787] ("Tapu Bulu") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[787];

export const grassyTerrain: SignatureDef = {
  id: "grassy_terrain",
  pokemonId: 787,
  species: "Tapu Bulu",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
