// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
import type { SignatureDef } from "./signature-def";
import { aeroblast } from "./aeroblast";
import { asOneGlacialReign } from "./as-one-glacial-reign";
import { asOneSpectralReign } from "./as-one-spectral-reign";
import { astralBarrageSteed } from "./astral-barrage-steed";
import { auroraVeil } from "./aurora-veil";
import { beastBoostBlacephalon } from "./beast-boost-blacephalon";
import { beastBoostNaganadel } from "./beast-boost-naganadel";
import { beastBoostPoipole } from "./beast-boost-poipole";
import { beastBoostStakataka } from "./beast-boost-stakataka";
import { beatUp } from "./beat-up";
import { behemothBash } from "./behemoth-bash";
import { behemothBlade } from "./behemoth-blade";
import { bleakwindStorm } from "./bleakwind-storm";
import { blizzard } from "./blizzard";
import { blueFlare } from "./blue-flare";
import { boltStrike } from "./bolt-strike";
import { bubbleBeam } from "./bubble-beam";
import { burningBulwark } from "./burning-bulwark";
import { chainedVigor } from "./chained-vigor";
import { collisionCourse } from "./collision-course";
import { coltsBlade } from "./colts-blade";
import { cosmicPower } from "./cosmic-power";
import { darkVoid } from "./dark-void";
import { diamondStorm } from "./diamond-storm";
import { doomDesire } from "./doom-desire";
import { doubleIronBash } from "./double-iron-bash";
import { dragonEnergy } from "./dragon-energy";
import { dynamaxCannon } from "./dynamax-cannon";
import { electricTerrain } from "./electric-terrain";
import { electroDrift } from "./electro-drift";
import { emotionFutureSight } from "./emotion-future-sight";
import { fieryWrath } from "./fiery-wrath";
import { flashCannonMeltan } from "./flash-cannon-meltan";
import { flashCannonRegisteel } from "./flash-cannon-registeel";
import { fleurCannon } from "./fleur-cannon";
import { focusEnergy } from "./focus-energy";
import { geomancy } from "./geomancy";
import { glacialLanceSteed } from "./glacial-lance-steed";
import { glaciate } from "./glaciate";
import { grassyTerrain } from "./grassy-terrain";
import { heartSwap } from "./heart-swap";
import { hydroSteam } from "./hydro-steam";
import { hyperspaceHole } from "./hyperspace-hole";
import { ivyCudgel } from "./ivy-cudgel";
import { judgment } from "./judgment";
import { jungleHealing } from "./jungle-healing";
import { killingFrost } from "./killing-frost";
import { knowledgeFutureSight } from "./knowledge-future-sight";
import { lunarDance } from "./lunar-dance";
import { lusterPurge } from "./luster-purge";
import { magmaStorm } from "./magma-storm";
import { malignantChain } from "./malignant-chain";
import { mightyCleave } from "./mighty-cleave";
import { mistBall } from "./mist-ball";
import { mistyTerrain } from "./misty-terrain";
import { moongeistBeam } from "./moongeist-beam";
import { oblivionWing } from "./oblivion-wing";
import { photonGeyser } from "./photon-geyser";
import { plasmaFists } from "./plasma-fists";
import { primordialDeluge } from "./primordial-deluge";
import { psyblade } from "./psyblade";
import { psychicTerrain } from "./psychic-terrain";
import { psychoBoost } from "./psycho-boost";
import { psystrike } from "./psystrike";
import { rainbowRebirth } from "./rainbow-rebirth";
import { relicSong } from "./relic-song";
import { rksAdaptation } from "./rks-adaptation";
import { roarOfTime } from "./roar-of-time";
import { rockCleavingBlade } from "./rock-cleaving-blade";
import { rollingThunder } from "./rolling-thunder";
import { ruinationBeads } from "./ruination-beads";
import { ruinationSword } from "./ruination-sword";
import { ruinationTablets } from "./ruination-tablets";
import { ruinationVessel } from "./ruination-vessel";
import { sacredFlame } from "./sacred-flame";
import { sandsearStorm } from "./sandsear-storm";
import { scorchedEarth } from "./scorched-earth";
import { seedFlare } from "./seed-flare";
import { shadowForce } from "./shadow-force";
import { skySplittingAscent } from "./sky-splitting-ascent";
import { slowStart } from "./slow-start";
import { sludgeWave } from "./sludge-wave";
import { spacialRend } from "./spacial-rend";
import { spectralThief } from "./spectral-thief";
import { splashUseless } from "./splash-useless";
import { steadfastBlade } from "./steadfast-blade";
import { steamEruption } from "./steam-eruption";
import { stoneEdge } from "./stone-edge";
import { sunsteelStrike } from "./sunsteel-strike";
import { surgingStrikes } from "./surging-strikes";
import { tachyonCutter } from "./tachyon-cutter";
import { technoBlast } from "./techno-blast";
import { teraStarstorm } from "./tera-starstorm";
import { thousandWaves } from "./thousand-waves";
import { thunderCage } from "./thunder-cage";
import { thunderclap } from "./thunderclap";
import { thunderousKick } from "./thunderous-kick";
import { timeTravel } from "./time-travel";
import { transform } from "./transform";
import { upperHand } from "./upper-hand";
import { verdantBlade } from "./verdant-blade";
import { victoryStar } from "./victory-star";
import { wildboltStorm } from "./wildbolt-storm";
import { willpowerFutureSight } from "./willpower-future-sight";

export type { SignatureDef } from "./signature-def";

export const SIGNATURE_LIST: readonly SignatureDef[] = [
  aeroblast,
  asOneGlacialReign,
  asOneSpectralReign,
  astralBarrageSteed,
  auroraVeil,
  beastBoostBlacephalon,
  beastBoostNaganadel,
  beastBoostPoipole,
  beastBoostStakataka,
  beatUp,
  behemothBash,
  behemothBlade,
  bleakwindStorm,
  blizzard,
  blueFlare,
  boltStrike,
  bubbleBeam,
  burningBulwark,
  chainedVigor,
  collisionCourse,
  coltsBlade,
  cosmicPower,
  darkVoid,
  diamondStorm,
  doomDesire,
  doubleIronBash,
  dragonEnergy,
  dynamaxCannon,
  electricTerrain,
  electroDrift,
  emotionFutureSight,
  fieryWrath,
  flashCannonMeltan,
  flashCannonRegisteel,
  fleurCannon,
  focusEnergy,
  geomancy,
  glacialLanceSteed,
  glaciate,
  grassyTerrain,
  heartSwap,
  hydroSteam,
  hyperspaceHole,
  ivyCudgel,
  judgment,
  jungleHealing,
  killingFrost,
  knowledgeFutureSight,
  lunarDance,
  lusterPurge,
  magmaStorm,
  malignantChain,
  mightyCleave,
  mistBall,
  mistyTerrain,
  moongeistBeam,
  oblivionWing,
  photonGeyser,
  plasmaFists,
  primordialDeluge,
  psyblade,
  psychicTerrain,
  psychoBoost,
  psystrike,
  rainbowRebirth,
  relicSong,
  rksAdaptation,
  roarOfTime,
  rockCleavingBlade,
  rollingThunder,
  ruinationBeads,
  ruinationSword,
  ruinationTablets,
  ruinationVessel,
  sacredFlame,
  sandsearStorm,
  scorchedEarth,
  seedFlare,
  shadowForce,
  skySplittingAscent,
  slowStart,
  sludgeWave,
  spacialRend,
  spectralThief,
  splashUseless,
  steadfastBlade,
  steamEruption,
  stoneEdge,
  sunsteelStrike,
  surgingStrikes,
  tachyonCutter,
  technoBlast,
  teraStarstorm,
  thousandWaves,
  thunderCage,
  thunderclap,
  thunderousKick,
  timeTravel,
  transform,
  upperHand,
  verdantBlade,
  victoryStar,
  wildboltStorm,
  willpowerFutureSight,
];

export const SIGNATURE_BY_ID: Record<string, SignatureDef> = {
  "aeroblast": aeroblast,
  "as_one_glacial_reign": asOneGlacialReign,
  "as_one_spectral_reign": asOneSpectralReign,
  "astral_barrage_steed": astralBarrageSteed,
  "aurora_veil": auroraVeil,
  "beast_boost_blacephalon": beastBoostBlacephalon,
  "beast_boost_naganadel": beastBoostNaganadel,
  "beast_boost_poipole": beastBoostPoipole,
  "beast_boost_stakataka": beastBoostStakataka,
  "beat_up": beatUp,
  "behemoth_bash": behemothBash,
  "behemoth_blade": behemothBlade,
  "bleakwind_storm": bleakwindStorm,
  "blizzard": blizzard,
  "blue_flare": blueFlare,
  "bolt_strike": boltStrike,
  "bubble_beam": bubbleBeam,
  "burning_bulwark": burningBulwark,
  "chained_vigor": chainedVigor,
  "collision_course": collisionCourse,
  "colts_blade": coltsBlade,
  "cosmic_power": cosmicPower,
  "dark_void": darkVoid,
  "diamond_storm": diamondStorm,
  "doom_desire": doomDesire,
  "double_iron_bash": doubleIronBash,
  "dragon_energy": dragonEnergy,
  "dynamax_cannon": dynamaxCannon,
  "electric_terrain": electricTerrain,
  "electro_drift": electroDrift,
  "emotion_future_sight": emotionFutureSight,
  "fiery_wrath": fieryWrath,
  "flash_cannon_meltan": flashCannonMeltan,
  "flash_cannon_registeel": flashCannonRegisteel,
  "fleur_cannon": fleurCannon,
  "focus_energy": focusEnergy,
  "geomancy": geomancy,
  "glacial_lance_steed": glacialLanceSteed,
  "glaciate": glaciate,
  "grassy_terrain": grassyTerrain,
  "heart_swap": heartSwap,
  "hydro_steam": hydroSteam,
  "hyperspace_hole": hyperspaceHole,
  "ivy_cudgel": ivyCudgel,
  "judgment": judgment,
  "jungle_healing": jungleHealing,
  "killing_frost": killingFrost,
  "knowledge_future_sight": knowledgeFutureSight,
  "lunar_dance": lunarDance,
  "luster_purge": lusterPurge,
  "magma_storm": magmaStorm,
  "malignant_chain": malignantChain,
  "mighty_cleave": mightyCleave,
  "mist_ball": mistBall,
  "misty_terrain": mistyTerrain,
  "moongeist_beam": moongeistBeam,
  "oblivion_wing": oblivionWing,
  "photon_geyser": photonGeyser,
  "plasma_fists": plasmaFists,
  "primordial_deluge": primordialDeluge,
  "psyblade": psyblade,
  "psychic_terrain": psychicTerrain,
  "psycho_boost": psychoBoost,
  "psystrike": psystrike,
  "rainbow_rebirth": rainbowRebirth,
  "relic_song": relicSong,
  "rks_adaptation": rksAdaptation,
  "roar_of_time": roarOfTime,
  "rock_cleaving_blade": rockCleavingBlade,
  "rolling_thunder": rollingThunder,
  "ruination_beads": ruinationBeads,
  "ruination_sword": ruinationSword,
  "ruination_tablets": ruinationTablets,
  "ruination_vessel": ruinationVessel,
  "sacred_flame": sacredFlame,
  "sandsear_storm": sandsearStorm,
  "scorched_earth": scorchedEarth,
  "seed_flare": seedFlare,
  "shadow_force": shadowForce,
  "sky_splitting_ascent": skySplittingAscent,
  "slow_start": slowStart,
  "sludge_wave": sludgeWave,
  "spacial_rend": spacialRend,
  "spectral_thief": spectralThief,
  "splash_useless": splashUseless,
  "steadfast_blade": steadfastBlade,
  "steam_eruption": steamEruption,
  "stone_edge": stoneEdge,
  "sunsteel_strike": sunsteelStrike,
  "surging_strikes": surgingStrikes,
  "tachyon_cutter": tachyonCutter,
  "techno_blast": technoBlast,
  "tera_starstorm": teraStarstorm,
  "thousand_waves": thousandWaves,
  "thunder_cage": thunderCage,
  "thunderclap": thunderclap,
  "thunderous_kick": thunderousKick,
  "time_travel": timeTravel,
  "transform": transform,
  "upper_hand": upperHand,
  "verdant_blade": verdantBlade,
  "victory_star": victoryStar,
  "wildbolt_storm": wildboltStorm,
  "willpower_future_sight": willpowerFutureSight,
};

export const SIGNATURE_BY_POKEMON_ID: Record<number, SignatureDef> = Object.fromEntries(
  SIGNATURE_LIST.map((d) => [d.pokemonId, d]),
);
