// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[480] ("Uxie") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[480];

export const knowledgeFutureSight: SignatureDef = {
  id: "knowledge_future_sight",
  pokemonId: 480,
  species: "Uxie",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
