// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[1025] ("Pecharunt") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[1025];

export const malignantChain: SignatureDef = {
  id: "malignant_chain",
  pokemonId: 1025,
  species: "Pecharunt",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
