// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[788] ("Tapu Fini") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[788];

export const mistyTerrain: SignatureDef = {
  id: "misty_terrain",
  pokemonId: 788,
  species: "Tapu Fini",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
