// GENERATED by scripts/gen-signature-content.ts — do not hand-edit.
// Wraps SIGNATURE_ABILITIES[145] ("Zapdos") from signature-abilities.ts.
// DO NOT hand-edit the spec here — regenerate from the catalog and verify with
// liveness.ts + a byte-identical balance-sim run (CLAUDE.md).
import type { SignatureDef } from "./signature-def";
import { SIGNATURE_ABILITIES } from "../../../lib/signature-abilities";
import { describeEngineSpec } from "../../../lib/signature-engine-describe";

const row = SIGNATURE_ABILITIES[145];

export const thunderousKick: SignatureDef = {
  id: "thunderous_kick",
  pokemonId: 145,
  species: "Zapdos",
  engine: row.engine!,
  describe: () => describeEngineSpec(row.engine!),
};
